//
//  Fastfile
//  CD
//
//  Created by Srikanth Kyatham on 1/20/25.
//

default_platform(:ios)

platform :ios do
  desc "Run tests for the project"
  lane :run_tests do
    scan(
      project: "CD.xcodeproj",
      scheme: "CD",
      devices: ["iPhone 14"]
    )
  end
end
